//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.luckofwise.zipsearch.view;

import android.app.Activity;
import android.content.Context;
import android.widget.TextView;
import com.luckofwise.zipsearch.R.id;
import com.luckofwise.zipsearch.R.layout;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class LocationRowView_
    extends LocationRowView
{

    private Context context_;
    private boolean mAlreadyInflated_ = false;

    public LocationRowView_(Context context) {
        super(context);
        init_();
    }

    private void init_() {
        context_ = getContext();
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
    }

    private void afterSetContentView_() {
        textViewAddress = ((TextView) findViewById(id.textViewAddress));
        textViewPostal = ((TextView) findViewById(id.textViewPostal));
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!mAlreadyInflated_) {
            mAlreadyInflated_ = true;
            inflate(getContext(), layout.row_location, this);
            afterSetContentView_();
        }
        super.onFinishInflate();
    }

    public static LocationRowView build(Context context) {
        LocationRowView_ instance = new LocationRowView_(context);
        instance.onFinishInflate();
        return instance;
    }

}
